<?php

namespace Database\Seeders;

use App\Models\Alumni;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class AlumniTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $alumnis = [
            [
                'nama' => 'alumni',
                'no_telp' => '0812345678',
                'alamat' => 'Kliningan, Bandung',
                'status' => 'Kuliah',
                'tanggal_lahir' => Carbon::parse('2000-01-01'),
                'foto_profile' => '',
                'id_jurusan' => NULL,
            ],
            [
                'nama' => 'Adisty Nazwa Revalina',
                'no_telp' => '081572025429',
                'alamat' => 'Bandung',
                'status' => 'Pelajar',
                'tanggal_lahir' => Carbon::parse('2005-01-11'),
                'angkatan' => 2022,
                'foto_profile' => '',
                'id_jurusan' => 1,
            ],
            [
                'nama' => 'Aisyah Nafilah Indra Putri',
                'no_telp' => '089633250989',
                'alamat' => 'Bandung',
                'status' => 'Pelajar',
                'tanggal_lahir' => Carbon::parse('2004-08-21'),
                'angkatan' => 2022,
                'foto_profile' => '',
                'id_jurusan' => 1,
            ],
            [
                'nama' => 'Andhika Bayu Ramadhany',
                'no_telp' => '087721433169',
                'alamat' => 'Bandung',
                'status' => 'Pelajar',
                'tanggal_lahir' => Carbon::parse('2005-10-19'),
                'angkatan' => 2022,
                'foto_profile' => '',
                'id_jurusan' => 1,
            ],
            [
                'nama' => 'Arsyl Slamet Amrulloh',
                'no_telp' => '087839376909',
                'alamat' => 'Bandung',
                'status' => 'Pelajar',
                'tanggal_lahir' => Carbon::parse('2004-10-03'),
                'angkatan' => 2022,
                'foto_profile' => '',
                'id_jurusan' => 1,
            ],
            [
                'nama' => 'Della',
                'no_telp' => '085871053008',
                'alamat' => 'Bandung',
                'status' => 'Pelajar',
                'tanggal_lahir' => Carbon::parse('2004-06-06'),
                'angkatan' => 2022,
                'foto_profile' => '',
                'id_jurusan' => 1,
            ],
            [
                'nama' => 'Dhafin Qinthara Khalish',
                'no_telp' => '085282611507',
                'alamat' => 'Bandung',
                'status' => 'Pelajar',
                'tanggal_lahir' => Carbon::parse('2004-09-08'),
                'angkatan' => 2022,
                'foto_profile' => '',
                'id_jurusan' => 1,
            ],
            [
                'nama' => 'Dio Fathir Zinedine Khalafa',
                'no_telp' => '085885073986',
                'alamat' => 'Bandung',
                'status' => 'Pelajar',
                'tanggal_lahir' => Carbon::parse('2004-07-22'),
                'angkatan' => 2022,
                'foto_profile' => '',
                'id_jurusan' => 1,
            ],
            [
                'nama' => 'Fairuztsani Kemal Setiawan',
                'no_telp' => 'Fairuztsani Kemal Setiawan ',
                'alamat' => 'Bandung',
                'status' => 'Pelajar',
                'tanggal_lahir' => Carbon::parse('2005-05-29'),
                'angkatan' => 2022,
                'foto_profile' => '',
                'id_jurusan' => 1,
            ],
            [
                'nama' => 'Fajri Zhahiran Wiriadinata',
                'no_telp' => '082128666732',
                'alamat' => 'Bandung',
                'status' => 'Pelajar',
                'tanggal_lahir' => Carbon::parse('2005-05-26'),
                'angkatan' => 2022,
                'foto_profile' => '',
                'id_jurusan' => 1,
            ],
            [
                'nama' => 'Fauzan Subagja',
                'no_telp' => '089665967064',
                'alamat' => 'Bandung',
                'status' => 'Pelajar',
                'tanggal_lahir' => Carbon::parse('2004-05-25'),
                'angkatan' => 2022,
                'foto_profile' => '',
                'id_jurusan' => 1,
            ],
            [
                'nama' => 'Gloria Loren Lawuredja',
                'no_telp' => '081324094750',
                'alamat' => 'Bandung',
                'status' => 'Pelajar',
                'tanggal_lahir' => Carbon::parse('2004-06-12'),
                'angkatan' => 2022,
                'foto_profile' => '',
                'id_jurusan' => 1,
            ],
            [
                'nama' => 'Iqbal Abdurrahman',
                'no_telp' => '083144791501',
                'alamat' => 'Bandung',
                'status' => 'Pelajar',
                'tanggal_lahir' => Carbon::parse('2004-10-13'),
                'angkatan' => 2022,
                'foto_profile' => '',
                'id_jurusan' => 1,
            ],
            [
                'nama' => 'Laila Al-Farah',
                'no_telp' => '085795042384',
                'alamat' => 'Bandung',
                'status' => 'Pelajar',
                'tanggal_lahir' => Carbon::parse('2004-11-26'),
                'angkatan' => 2022,
                'foto_profile' => '',
                'id_jurusan' => 1,
            ],
            [
                'nama' => 'Luthfi Satrio Wicaksono',
                'no_telp' => '087722582430',
                'alamat' => 'Bandung',
                'status' => 'Pelajar',
                'tanggal_lahir' => Carbon::parse('2005-03-12'),
                'angkatan' => 2022,
                'foto_profile' => '',
                'id_jurusan' => 1,
            ],
            [
                'nama' => 'Mochamad Daffa',
                'no_telp' => '089630840739',
                'alamat' => 'Bandung',
                'status' => 'Pelajar',
                'tanggal_lahir' => Carbon::parse('2005-02-20'),
                'angkatan' => 2022,
                'foto_profile' => '',
                'id_jurusan' => 1,
            ],
            [
                'nama' => 'Muhammad Ali Nur Rohman',
                'no_telp' => '08810236055960',
                'alamat' => 'Bandung',
                'status' => 'Pelajar',
                'tanggal_lahir' => Carbon::parse('2004-04-23'),
                'angkatan' => 2022,
                'foto_profile' => '',
                'id_jurusan' => 1,
            ],
            [
                'nama' => 'Muhammad Farras Fikri W.',
                'no_telp' => '087804824879',
                'alamat' => 'Bandung',
                'status' => 'Pelajar',
                'tanggal_lahir' => Carbon::parse('2005-08-12'),
                'angkatan' => 2022,
                'foto_profile' => '',
                'id_jurusan' => 1,
            ],
            [
                'nama' => 'Muhammad Favian Jiwani',
                'no_telp' => '082117773811',
                'alamat' => 'Bandung',
                'status' => 'Pelajar',
                'tanggal_lahir' => Carbon::parse('2005-04-25'),
                'angkatan' => 2022,
                'foto_profile' => '',
                'id_jurusan' => 1,
            ],
            [
                'nama' => 'Muhammad Ilham Fathurrohim Alba',
                'no_telp' => '071220928202 ',
                'alamat' => 'Bandung',
                'status' => 'Pelajar',
                'tanggal_lahir' => Carbon::parse('2005-07-17'),
                'angkatan' => 2022,
                'foto_profile' => '',
                'id_jurusan' => 1,
            ],
            [
                'nama' => 'Muhammad Jilan Satria',
                'no_telp' => '089655704929',
                'alamat' => 'Bandung',
                'status' => 'Pelajar',
                'tanggal_lahir' => Carbon::parse('2005-09-18'),
                'angkatan' => 2022,
                'foto_profile' => '',
                'id_jurusan' => 1,
            ],
            [
                'nama' => 'M.Raditya Pradana Ilhami',
                'no_telp' => '083871499094',
                'alamat' => 'Bandung',
                'status' => 'Pelajar',
                'tanggal_lahir' => Carbon::parse('2004-12-26'),
                'angkatan' => 2022,
                'foto_profile' => '',
                'id_jurusan' => 1,
            ],
            [
                'nama' => 'Muhammad Nazriel Alfarizi',
                'no_telp' => '089508900031',
                'alamat' => 'Bandung',
                'status' => 'Pelajar',
                'tanggal_lahir' => Carbon::parse('2005-02-13'),
                'angkatan' => 2022,
                'foto_profile' => '',
                'id_jurusan' => 1,
            ],
            [
                'nama' => 'Nabila Aulia Sapitri',
                'no_telp' => '081313971583',
                'alamat' => 'Bandung',
                'status' => 'Pelajar',
                'tanggal_lahir' => Carbon::parse('2005-02-01'),
                'angkatan' => 2022,
                'foto_profile' => '',
                'id_jurusan' => 1,
            ],
            [
                'nama' => 'Nadhil Wirasetya Andariki',
                'no_telp' => '087880077120',
                'alamat' => 'Bandung',
                'status' => 'Pelajar',
                'tanggal_lahir' => Carbon::parse('2004-10-02'),
                'angkatan' => 2022,
                'foto_profile' => '',
                'id_jurusan' => 1,
            ],
            [
                'nama' => 'Naufal Nur Hafizh',
                'no_telp' => '089658491262',
                'alamat' => 'Bandung',
                'status' => 'Pelajar',
                'tanggal_lahir' => Carbon::parse('2005-01-10'),
                'angkatan' => 2022,
                'foto_profile' => '',
                'id_jurusan' => 1,
            ],
            [
                'nama' => 'Raaqi Athaulla',
                'no_telp' => '085219504630',
                'alamat' => 'Bandung',
                'status' => 'Pelajar',
                'tanggal_lahir' => Carbon::parse('2005-10-14'),
                'angkatan' => 2022,
                'foto_profile' => '',
                'id_jurusan' => 1,
            ],
            [
                'nama' => 'Raditya Kanahaya',
                'no_telp' => '08112255991',
                'alamat' => 'Bandung',
                'status' => 'Pelajar',
                'tanggal_lahir' => Carbon::parse('2006-07-13'),
                'angkatan' => 2022,
                'foto_profile' => '',
                'id_jurusan' => 1,
            ],
            [
                'nama' => 'Rangga Ramadhan',
                'no_telp' => '083843674629',
                'alamat' => 'Bandung',
                'status' => 'Pelajar',
                'tanggal_lahir' => Carbon::parse('2003-10-14'),
                'angkatan' => 2022,
                'foto_profile' => '',
                'id_jurusan' => 1,
            ],
            [
                'nama' => 'Rhiza',
                'no_telp' => '089601975166',
                'alamat' => 'Bandung',
                'status' => 'Pelajar',
                'tanggal_lahir' => Carbon::parse('2005-10-29'),
                'angkatan' => 2022,
                'foto_profile' => '',
                'id_jurusan' => 1,
            ],
            [
                'nama' => 'Silmi Julia Rahmi',
                'no_telp' => 'Silmi Julia Rahmi ',
                'alamat' => 'Bandung',
                'status' => 'Pelajar',
                'tanggal_lahir' => Carbon::parse('2004-07-21'),
                'angkatan' => 2022,
                'foto_profile' => '',
                'id_jurusan' => 1,
            ],
            [
                'nama' => 'Stefhanie Valentina',
                'no_telp' => '08986993124',
                'alamat' => 'Bandung',
                'status' => 'Pelajar',
                'tanggal_lahir' => Carbon::parse('2005-07-10'),
                'angkatan' => 2022,
                'foto_profile' => '',
                'id_jurusan' => 1,
            ],
            [
                'nama' => 'Tharissa Shalsabila Trihapsari',
                'no_telp' => 'Tharissa Shalsabila Trihapsari ',
                'alamat' => 'Bandung',
                'status' => 'Pelajar',
                'tanggal_lahir' => Carbon::parse('2005-10-03'),
                'angkatan' => 2022,
                'foto_profile' => '',
                'id_jurusan' => 1,
            ],
            [
                'nama' => 'Wisnu Adi Pradana',
                'no_telp' => '085730108305',
                'alamat' => 'Bandung',
                'status' => 'Pelajar',
                'tanggal_lahir' => Carbon::parse('2004-10-20'),
                'angkatan' => 2022,
                'foto_profile' => '',
                'id_jurusan' => 1,
            ],
            [
                'nama' => 'Yolanda Belva Daniswara',
                'no_telp' => '089656447292',
                'alamat' => 'Bandung',
                'status' => 'Pelajar',
                'tanggal_lahir' => Carbon::parse('2004-08-05'),
                'angkatan' => 2022,
                'foto_profile' => '',
                'id_jurusan' => 1,
            ],
        ];

        foreach($alumnis as $alumni){
            Alumni::create($alumni);
    }
}
}